/* PortableLM GitHub Pages service worker: isolation headers + app-shell caching. */
const CACHE_VERSION='portablelm-pages-1.6.4-connector-v1';
const rel=path=>new URL(path,self.registration.scope).href;
const INDEX_URL=rel('./index.html');
const CORE_URLS=[rel("./index.html"),rel("./manifest.webmanifest"),rel("./icons/icon.svg"),rel("./assets/app-loader.js"),rel("./assets/register-service-worker.js"),rel("./site/page-01.txt"),rel("./site/page-02.txt"),rel("./site/page-03.txt"),rel("./site/page-04.txt"),rel("./site/page-05.txt"),rel("./assets/app-01.txt"),rel("./assets/app-02.txt"),rel("./assets/app-03.txt"),rel("./assets/app-04.txt"),rel("./assets/app-05.txt"),rel("./assets/app-06.txt"),rel("./assets/app-07.txt"),rel("./assets/app-08.txt"),rel("./assets/app-09.txt")];
function isolatedResponse(response){if(!response||response.type==='opaque')return response;const headers=new Headers(response.headers);headers.set('Cross-Origin-Opener-Policy','same-origin');headers.set('Cross-Origin-Embedder-Policy','require-corp');headers.set('Cross-Origin-Resource-Policy','same-origin');return new Response(response.body,{status:response.status,statusText:response.statusText,headers});}
async function fetchAndCache(request,cacheKey=request){const response=await fetch(request);if(response&&response.ok){const cache=await caches.open(CACHE_VERSION);await cache.put(cacheKey,response.clone());}return isolatedResponse(response);}
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil((async()=>{const cache=await caches.open(CACHE_VERSION);for(const url of CORE_URLS){try{const response=await fetch(url,{cache:'reload'});if(response.ok)await cache.put(url,response);}catch(error){console.warn('PortableLM precache failed for',url,error);}}})());});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key!==CACHE_VERSION).map(key=>caches.delete(key)));await self.clients.claim();})());});
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.cache==='only-if-cached'&&request.mode!=='same-origin')return;event.respondWith((async()=>{const cache=await caches.open(CACHE_VERSION);if(request.mode==='navigate'){const cached=await cache.match(INDEX_URL);if(cached){event.waitUntil(fetchAndCache(request,INDEX_URL).catch(()=>undefined));return isolatedResponse(cached.clone());}return fetchAndCache(request,INDEX_URL);}const cached=await cache.match(request);if(cached){event.waitUntil(fetchAndCache(request).catch(()=>undefined));return isolatedResponse(cached.clone());}return fetchAndCache(request);})());});
